// <auto-generated />
namespace TrashCollector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedExtraPickup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedExtraPickup));
        
        string IMigrationMetadata.Id
        {
            get { return "201910311435420_AddedExtraPickup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
